-- Add advanced settings to quizzes
ALTER TABLE quizzes
ADD COLUMN IF NOT EXISTS access_password TEXT,
ADD COLUMN IF NOT EXISTS strict_mode BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS allow_backtracking BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS questions_per_page INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS allow_bookmarks BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS show_question_nav BOOLEAN NOT NULL DEFAULT TRUE;
